name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: |
          rm -f $GITHUB_WORKSPACE/builds/*.cs3
          rm -f $GITHUB_WORKSPACE/builds/*.jar

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Android SDK manually
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends unzip wget tar
          mkdir -p "$HOME/android-sdk"
          cd "$HOME/android-sdk"
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Create local.properties
        run: |
          echo "sdk.dir=$HOME/android-sdk" > $GITHUB_WORKSPACE/src/local.properties

      - name: Grant gradlew permission
        run: |
          chmod +x $GITHUB_WORKSPACE/src/gradlew

      - name: Build with Gradle
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds || true
          cp local.properties $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
