name: Build Cloudstream Extension

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Gradle 8.12
      run: |
        wget https://services.gradle.org/distributions/gradle-8.12-bin.zip
        unzip gradle-8.12-bin.zip
        sudo mv gradle-8.12 /opt/gradle
        sudo rm -f /usr/bin/gradle   # Remove existing symlink or binary if present
        sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle
        gradle -v

    - name: Build Cloudstream Extension
      run: |
        ./gradlew clean assembleRelease --stacktrace
