name: Build Cloudstream Plugins

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write local.properties for StreamPlay only
        env:
          StreamPlayAPI: ${{ secrets.StreamPlayAPI }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo "StreamPlayAPI=$StreamPlayAPI" > local.properties

      - name: Grant execute permission for gradlew
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew make makePluginsJson

      - name: Copy build artifacts
        run: |
          mkdir -p $GITHUB_WORKSPACE/builds
          cp $GITHUB_WORKSPACE/src/**/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp $GITHUB_WORKSPACE/src/**/build/*.jar $GITHUB_WORKSPACE/builds || true
          cp $GITHUB_WORKSPACE/src/build/plugins.json $GITHUB_WORKSPACE/builds || true

      - name: List builds folder
        run: ls -la $GITHUB_WORKSPACE/builds
