name: Build DhakaFlix Plugins

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_TOKEN: ${{ secrets.DHAKAFLIX_TOKEN }}

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"
          token: ${{ secrets.DHAKAFLIX_TOKEN }}

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK (manual)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build plugins
        run: |
          cd src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/
          cp build/plugins.json $GITHUB_WORKSPACE/builds/

      - name: Push to builds branch
        run: |
          cd builds
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || echo "No changes to commit"
          git push --force "https://${{ secrets.DHAKAFLIX_TOKEN }}@github.com/ALLBYNAJID/DhakaFlix_Cloudstream.git" HEAD:builds
