name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '33'

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Create local.properties
        run: |
          echo "sdk.dir=$HOME/android-sdk" > local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: StreamPlay-debug-apk
          path: app/build/outputs/apk/debug/*.apk
