name: Build Plugins and Push to DhakaFlix_Cloudstream

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          path: src

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          mkdir -p $GITHUB_WORKSPACE/builds
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push to DhakaFlix_Cloudstream repo
        run: |
          cd $GITHUB_WORKSPACE/builds
          git init
          git checkout -b builds
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote add origin https://x-access-token:${{ secrets.DHAKAFLIX_TOKEN }}@github.com/ALLBYNAJID/DhakaFlix_Cloudstream.git
          git add .
          git commit -m "Update plugins.json from cloudstream"
          git push --force origin builds
