name: Build Extensions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build all extensions
        run: ./gradlew build

      - name: Upload built extensions
        uses: actions/upload-artifact@v4
        with:
          name: built-extensions
          path: |
            */build/outputs/*.zip
