name: Build Cloudstream Extension

on:
  push:
    branches:
      - main
    paths:
      - 'StreamPlay/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          # Additional setup commands as needed

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.12-bin.zip
          unzip gradle-8.12-bin.zip
          sudo mv gradle-8.12 /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle

      - name: Generate local.properties
        run: |
          echo "sdk.dir=/usr/lib/android-sdk" > local.properties

      - name: Build StreamPlay extension
        run: |
          cd StreamPlay
          ./gradlew build
