name: Build All Plugins

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main source
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./src/gradlew

      - name: Build all plugins & generate plugins.json
        run: |
          cd src
          ./gradlew clean make makePluginsJson
          # Copy all generated .cs3 files to builds folder
          find . -name "*.cs3" -exec cp {} ../builds/ \;
          # Copy plugins.json to builds folder
          cp build/plugins.json ../builds/plugins.json

      - name: Commit and push to builds branch
        run: |
          cd builds
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Build plugins $GITHUB_SHA"
          git push origin builds
